#!usr/bin/env python3
# file_fun.py
# Author: Colin Ries
#
# This contrived script is an exploration of python 3.x native file functions


def write_csv(n):
    """Generate a csv file containing the first n natural numbers

    Generate a csv file containing the first n natural numbers, starting with
    0.
    """
    out = ''
    for i in range(0, n+1):
        out = out + str(i) + '\n'
    # print(out)

    with open('file_fun.csv', 'w+') as output:
        output.write(out)


def read_csv(m):
    """Read first m lines of csv file generated by write_csv"""
    lst = list(range(m))
    num = generate_fib()

    with open('file_fun.csv', 'r') as input_file:
        for i in range(0, m):
            lst[i] = input_file.readline()

    return lst


def generate_fib():
    """Generate the next Fibonacci number"""
    # Credit for design goes to John La Rooy, Gaurav Kumar on Stack Overflow
    # https://stackoverflow.com/questions/3953749/python-fibonacci-generator
    a, b = 0, 1
    while True:
        yield a
        b += a
        yield b
        a += b


def test():
    write_csv(40)
    seq = read_csv(20)
    for i in range(10):
        print(seq[i], end='')


if __name__ == '__main__':
    test()
